version: '3.0'
networks:
  default:
    driver: bridge
    attachable: true
services:
  cribl_workers:
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster_secret@master_host:4200 ### Update this setting with the IP address and port of your cribl worker
    ports:
      - 9000
      - "9998:9998"
      - "8088:8088"
      - "10090:10090"
      - "1514:1514"
      - "1514:1514/udp"
    deploy:
        resources:
            limits:
              cpus: '3.00'
              memory: 2048M
